version: 0.0
os: linux
files:
  - source: deploy/config.env
    destination: /opt/retailedge
  - source: deploy/scripts/deploy-container.sh
    destination: /opt/retailedge/scripts
hooks:
  ApplicationStop:
    - location: deploy/scripts/stop-container.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: deploy/scripts/deploy-container.sh
      timeout: 600
      runas: root
